BEGIN;
ALTER TABLE "SystemConfig" DROP CONSTRAINT IF EXISTS "SystemConfig_updatedBy_fkey";
ALTER TABLE "ParentVerificationToken" DROP CONSTRAINT IF EXISTS "ParentVerificationToken_parentId_fkey";
ALTER TABLE "AbsenceRequest" DROP CONSTRAINT IF EXISTS "AbsenceRequest_teacherId_fkey", DROP CONSTRAINT IF EXISTS "AbsenceRequest_parentId_fkey", DROP CONSTRAINT IF EXISTS "AbsenceRequest_studentId_fkey";
ALTER TABLE "PaymentRecord" DROP CONSTRAINT IF EXISTS "PaymentRecord_parentId_fkey", DROP CONSTRAINT IF EXISTS "PaymentRecord_studentId_fkey";
ALTER TABLE "SecurityAudit" DROP CONSTRAINT IF EXISTS "SecurityAudit_userId_fkey";
ALTER TABLE "TokenRevocation" DROP CONSTRAINT IF EXISTS "TokenRevocation_userId_fkey";
ALTER TABLE "NotificationRecord" DROP CONSTRAINT IF EXISTS "NotificationRecord_senderId_fkey", DROP CONSTRAINT IF EXISTS "NotificationRecord_recipientId_fkey";
ALTER TABLE "StoredFileRecord" DROP CONSTRAINT IF EXISTS "StoredFileRecord_uploadedById_fkey";
ALTER TABLE "NotificationRecord" DROP CONSTRAINT IF EXISTS "NotificationRecord_type_check", DROP CONSTRAINT IF EXISTS "NotificationRecord_severity_check", DROP CONSTRAINT IF EXISTS "NotificationRecord_category_check";
ALTER TABLE "AbsenceRequest" DROP CONSTRAINT IF EXISTS "AbsenceRequest_status_check", DROP CONSTRAINT IF EXISTS "AbsenceRequest_date_order_check";
ALTER TABLE "PaymentRecord" DROP CONSTRAINT IF EXISTS "PaymentRecord_status_check", DROP CONSTRAINT IF EXISTS "PaymentRecord_amount_check";
ALTER TABLE "QuizAttemptSession" DROP CONSTRAINT IF EXISTS "QuizAttemptSession_status_check";
ALTER TABLE "Quiz" DROP CONSTRAINT IF EXISTS "Quiz_reveal_marks_mode_check";
ALTER TABLE "Submission" DROP CONSTRAINT IF EXISTS "Submission_status_check", DROP CONSTRAINT IF EXISTS "Submission_grade_check";
ALTER TABLE "AttendanceRecord" DROP CONSTRAINT IF EXISTS "AttendanceRecord_status_check";
ALTER TABLE "TermProgress" DROP CONSTRAINT IF EXISTS "TermProgress_score_check";
ALTER TABLE "SubjectPerformance" DROP CONSTRAINT IF EXISTS "SubjectPerformance_score_check";
ALTER TABLE "QuizQuestion" DROP CONSTRAINT IF EXISTS "QuizQuestion_points_check";
ALTER TABLE "Assignment" DROP CONSTRAINT IF EXISTS "Assignment_total_points_check";
ALTER TABLE "Classroom" DROP CONSTRAINT IF EXISTS "Classroom_capacity_check";
ALTER TABLE "StudentProfile" DROP CONSTRAINT IF EXISTS "StudentProfile_nonnegative_progress_check";
ALTER TABLE "Attachment" DROP CONSTRAINT IF EXISTS "Attachment_exactly_one_owner_check";
DROP INDEX IF EXISTS "AbsenceRequest_teacherId_status_idx";
DROP INDEX IF EXISTS "AbsenceRequest_parentId_status_idx";
DROP INDEX IF EXISTS "PaymentRecord_parentId_createdAt_idx";
DROP INDEX IF EXISTS "NotificationRecord_senderId_idx";
DROP INDEX IF EXISTS "NotificationRecord_recipientId_read_createdAt_idx";
DROP INDEX IF EXISTS "AttendanceRecord_studentId_date_key";
DROP INDEX IF EXISTS "QuizSubmission_studentId_completedAt_idx";
DROP INDEX IF EXISTS "QuizSubmission_quizId_studentId_attemptNumber_key";
DROP INDEX IF EXISTS "Submission_assignmentId_studentId_key";
ALTER TABLE "StoredFileRecord" DROP COLUMN IF EXISTS "uploadedById";
COMMIT;
